### ISSUE TITLE
Build fails on windows

### ISSUE THREAD

**Issue by FreakTheMighty** [NormandErwan/ArucoUnity#18]
First of all, thanks for this library. I'm very excited to give it a try. I'm trying to build on windows 10 following the direction from [here](https://normanderwan.github.io/ArucoUnity/manual/build-from-sources.html). The first step completes successfully, but it fails on the second step. Below are the commands I've used and the output.

```powershell
$ cd ArucoUnity\ArucoUnityPlugin\build\opencv
$ cmake -DCMAKE_INSTALL_PREFIX=install/ -G "Visual Studio 15 2017 Win64" ..\..\3rdparty\opencv_contrib
$ cmake --build . --config Release

$ cd ArucoUnity\ArucoUnityPlugin\build
$ cmake -DCMAKE_INSTALL_PREFIX=.. -DOpenCV_DIR=../../build/opencv/install/ - "Visual Studio 15 2017 Win64" ..
```

Output 

```powershell
-- OpenCV ARCH: x86
-- OpenCV RUNTIME: vc14
-- OpenCV STATIC: OFF
CMake Warning at build/opencv/install/OpenCVConfig.cmake:156 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:31 (find_package)


CMake Error at CMakeLists.txt:31 (find_package):
  Found package configuration file:

    ArucoUnity/ArucoUnityPlugin/build/opencv/install/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.


-- Configuring incomplete, errors occurred!
See also "/ArucoUnity/ArucoUnityPlugin/build/CMakeFiles/CMakeOutput.log".
```

**Comment by NormandErwan** [comment]
I moved the ArucoUnityPlugin to a [dedicated repository](https://github.com/NormandErwan/ArucoUnityPlugin) and set-up automatic build both for Linux (with Travis) and Windows (with AppVeyor). You can download the plugin on [releases](https://github.com/NormandErwan/ArucoUnityPlugin/releases).

I also updated the documentation. It should be better now if you want to build the plugin by yourself.

**Comment by FreakTheMighty** [comment]
@NormandErwan thanks for the update. I ended up using python binding + sockets which worked for my purpose. If I have an opportunity to do this sort of thing again I'll report back my results. Thank you for your help.
